name: Docker Build
on:
  release:
    types: [ published ]
  workflow_dispatch:
env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}
  # Account to log into the repo as
  USERNAME: ${{ github.repository_owner }}

jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
      attestations: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write
    strategy:
      matrix:
        lua: [
          {package: lua51,  tag: 5.1, latest: true},
          {package: lua52,  tag: 5.2, latest: false},
          {package: lua53,  tag: 5.3, latest: false},
          {package: lua54,  tag: 5.4, latest: false},
          {package: luajit, tag: jit, latest: false}
        ]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - name: Setup cachix
        uses: cachix/cachix-action@v16
        with:
          name: neorocks
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Build Docker image
        id: build
        run: | # result-docker-lua51 is a symlink to the nix store
            nix build ".#lux-${{ matrix.lua.package }}-docker" --accept-flake-config -Lv --out-link result-docker-${{ matrix.lua.package }}
            docker load -i result-docker-${{ matrix.lua.package }}
      - name: Extract the image tag
        id: tag
        run: echo "tag=$(docker images --format '{{.Tag}}' ${{ env.IMAGE_NAME }} | head -n 1)" >> $GITHUB_OUTPUT
      - name: Move images to be from ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        run: |
          # Testing:
            echo "Tags: ${{ steps.tag.outputs.tags }}"
          docker tag ${{ env.IMAGE_NAME }}:${{ steps.tag.outputs.tag }} ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.tag.outputs.tag }}
          docker tag ${{ env.IMAGE_NAME }}:${{ steps.tag.outputs.tag }} ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ matrix.lua.tag }}
          docker rmi ${{ env.IMAGE_NAME }}:${{ steps.tag.outputs.tag }}
      - name: Make the `latest` tag point to the latest Lua version
        if: matrix.lua.latest == true
        run: |
          docker tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ matrix.lua.tag }} ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
      - name: Extract metadata (tags, labels) for Push
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Install cosign
        uses: sigstore/cosign-installer@59acb6260d9c0ba8f4a2f9d9b48431a222b68e20 #v3.5.0
        with:
          cosign-release: 'v2.2.4'
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
